include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/**/*.g.dart"
    - "**/**/*.gen.dart"
    - "**/**/*.freezed.dart"

linter:
  rules:
    - cancel_subscriptions
    - prefer_relative_imports
    - directives_ordering